# Generated by Django 5.2.14 on 2026-06-01 14:38

import bgp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgp', '0004_aspath_prefixlist'),
        # bgp_community is physically created by this peering move migration
        ('peering', '0108_move_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'communities'},
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='community',
            name='value',
            field=bgp.fields.CommunityField(blank=True, max_length=50, null=True),
        ),
    ]
