# Generated by Django 5.2.14 on 2026-05-30 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0108_move_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingpolicy',
            name='default_action',
            field=models.CharField(default='reject', max_length=50),
        ),
        migrations.CreateModel(
            name='PolicyTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('action', models.CharField(default='accept', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('routing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='peering.routingpolicy')),
            ],
            options={
                'ordering': ['routing_policy', 'sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TermAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('action_type', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='peering.policyterm')),
            ],
            options={
                'ordering': ['term', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('match_type', models.CharField(max_length=64)),
                ('values', models.JSONField(blank=True, default=list)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='peering.policyterm')),
            ],
            options={
                'verbose_name_plural': 'term matches',
                'ordering': ['term', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='policyterm',
            constraint=models.UniqueConstraint(fields=('routing_policy', 'name'), name='peering_policyterm_unique_name_per_policy'),
        ),
    ]
