# Generated by Django 5.2.14 on 2026-05-30 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0109_routingpolicy_default_action_policyterm_termaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('snapshot', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('routing_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='peering.routingpolicy')),
            ],
            options={
                'ordering': ['-created', '-id'],
            },
        ),
    ]
