# Generated by Django 5.2.14 on 2026-05-31 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_platform_arista_type7'),
        ('peering', '0110_routingpolicyversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingpolicy',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_policies', to='devices.router'),
        ),
    ]
