# Generated by Django 5.2.14 on 2026-05-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgp', '0004_aspath_prefixlist'),
        ('devices', '0011_platform_arista_type7'),
        ('extras', '0021_ixapi_api_url_field'),
        ('peering', '0111_routingpolicy_router'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingpolicy',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routingpolicy',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(fields=('router', 'name'), name='peering_routingpolicy_unique_name_per_router'),
        ),
        migrations.AddConstraint(
            model_name='routingpolicy',
            constraint=models.UniqueConstraint(fields=('router', 'slug'), name='peering_routingpolicy_unique_slug_per_router'),
        ),
    ]
