# Generated by Django 5.2.14 on 2026-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0112_alter_routingpolicy_name_alter_routingpolicy_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingpolicy',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
