# Generated by Django 5.2.14 on 2026-06-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peering', '0113_routingpolicy_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingpolicy',
            name='nos',
            field=models.CharField(default='nokia', max_length=50),
        ),
    ]
